query PullRequest($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    nameWithOwner
    pullRequest(number: $number) {
      id
      number
      state
      title
      body
      isDraft
      baseRefName
      headRefName
      baseRefOid
      headRefOid
      mergeable
      mergeStateStatus
      autoMergeRequest {
        enabledAt
      }
      mergeCommit {
        oid
      }
      latestOpinionatedReviews(last: 50) {
        nodes {
          state
          author {
            login
          }
        }
      }
      commits(last: 1) {
        nodes {
          commit {
            statusCheckRollup {
              contexts(first: 100) {
                checkRunCountsByState {
                  state
                  count
                }
                statusContextCountsByState {
                  state
                  count
                }
                nodes {
                  ... on CheckRun {
                    name
                    conclusion
                  }
                  ... on StatusContext {
                    context
                    state
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
